services:

  nginx:
    image: orthancteam/orthanc-nginx:24.5.1
    depends_on: [orthanc, orthanc-auth-service]
    restart: unless-stopped
    ports: ["8080:80"]
    environment:
      ENABLE_ORTHANC: "true"
      ENABLE_KEYCLOAK: "true"
      ENABLE_ORTHANC_TOKEN_SERVICE: "false"

  orthanc:
    image: orthancteam/orthanc:24.5.1
    volumes:
      - ./orthanc-admin.jsonc:/etc/orthanc/orthanc-admin.json
      - ./orthanc-common.jsonc:/etc/orthanc/orthanc-common.json
      - orthanc-data:/var/lib/orthanc/db:Z
    restart: unless-stopped
    environment:
      ORTHANC__NAME: "DGSA"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__STUDY_LIST_SEARCH_MODE: "search-button"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__STUDY_LIST_CONTENT_IF_NO_SEARCH: "empty"
      ORTHANC__ORTHANC_EXPLORER_2__IS_DEFAULT_ORTHANC_UI: "true"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__SHOW_SAME_PATIENT_STUDIES_FILTER: |
        ["PatientBirthDate", "PatientID"]
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      ORTHANC__STONE_WEB_VIEWER__SHOW_INFO_PANEL_AT_STARTUP: "Never"
      ORTHANC__DICOM_WEB__PUBLIC_ROOT: "/orthanc/dicom-web/"
      ORTHANC__DATABASE_SERVER_IDENTIFIER: "orthanc1"
      ORTHANC__POSTGRESQL__ENABLE_INDEX: "true"
      ORTHANC__POSTGRESQL__HOST: "postgres"
      ORTHANC__POSTGRESQL__INDEX_CONNECTIONS_COUNT: 50
      ORTHANC__POSTGRESQL__TRANSACTION_MODE: "ReadCommitted"
      ORTHANC__POSTGRESQL__ENABLE_STORAGE: "false"
      ORTHANC__AUTHORIZATION__WEB_SERVICE_PASSWORD: "change-me"
      ORTHANC__AUTHORIZATION__WEB_SERVICE_USER_NAME: "share-user"

  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes: ["orthanc-index:/var/lib/postgresql/data:Z"] 
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  orthanc-auth-service:
    image: orthancteam/orthanc-auth-service:24.5.1
    depends_on: [keycloak]
    restart: unless-stopped
    environment:
      ENABLE_KEYCLOAK: "true"
      KEYCLOAK_URI: "http://keycloak:8080/realms/orthanc"
      PUBLIC_ORTHANC_ROOT: "https://dgsa.lat/orthanc/"
      PUBLIC_LANDING_ROOT: "https://dgsa.lat/orthanc/ui/app/token-landing.html"
      PERMISSIONS_FILE_PATH: "/orthanc_auth_service/permissions.json"
        # ENABLE_KEYCLOAK_API_KEYS: "true"
        #KEYCLOAK_CLIENT_SECRET: "6zIUEpAKjp9F7cljhnFyHxU6OMPbOj0n"
      SECRET_KEY: "dgsa1757"
      USERS: |
        {
          "share-user": "change-me"
        }

    volumes:
      - ./permissions.json:/orthanc_auth_service/permissions.json
    
  keycloak:
    image: orthancteam/orthanc-keycloak:24.5.1
    depends_on: [keycloak-db]
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "dgsa1757"
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://keycloak-db:5432/keycloak"
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: "keycloak"
      KC_HOSTNAME_URL: "https://dgsa.lat/keycloak"
      KC_HOSTNAME_ADMIN_URL: "https://dgsa.lat/keycloak"

  keycloak-db:
    image: postgres:14
    restart: unless-stopped
    volumes: ["keycloak-db:/var/lib/postgresql/data"]
    environment:
      POSTGRES_PASSWORD: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_DB: "keycloak"

volumes:
  keycloak-db:
  orthanc-data:
  orthanc-index:

